name: CI

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: npm i

    - name: ESLint checks
      run: npm run lint

  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: npm i

    - name: Jest
      run: npm run test
